//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace KHCNCT.Web.SiteEntities.Pages {
    
    
    public partial class trang_chu {
        
        /// <summary>
        /// TinNoiBat1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KHCNCT.Web.SiteEntities.Modules.tin_noi_bat TinNoiBat1;
        
        /// <summary>
        /// ThongBao1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KHCNCT.Web.SiteEntities.Modules.thong_bao ThongBao1;
        
        /// <summary>
        /// XemNhieu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KHCNCT.Web.SiteEntities.Modules.xem_nhieu XemNhieu1;
        
        /// <summary>
        /// TinChuyenMucTrangChu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KHCNCT.Web.SiteEntities.Modules.tin_chuyen_muc_trang_chu TinChuyenMucTrangChu1;
        
        /// <summary>
        /// VideoTrangChu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KHCNCT.Modules.video_trang_chu VideoTrangChu1;
        
        /// <summary>
        /// ThuTucHanhChinh1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KHCNCT.Web.SiteEntities.Modules.thu_tuc_hanh_chinh_home ThuTucHanhChinh1;
        
        /// <summary>
        /// VanBanPhapQuy1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KHCNCT.Web.SiteEntities.Modules.van_ban_phap_quy_home VanBanPhapQuy1;
        
        /// <summary>
        /// TinTheoChuyenMucT23 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KHCNCT.Web.SiteEntities.Modules.tin_theo_chuyen_muc_t2 TinTheoChuyenMucT23;
    }
}
