//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AccountMessage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rất tiếc bạn không có quyền truy cập mục này.Liên hệ quản trị để biết thêm chi tiết!.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được kích hoạt thành công. &lt;br /&gt; Click vào &lt;a href=&quot;/?page=login&quot;&gt;đây&lt;/a&gt; để đăng nhập hệ thống.
        /// </summary>
        internal static string AccountActivateSuccess {
            get {
                return ResourceManager.GetString("AccountActivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được kích hoạt rồi.
        /// </summary>
        internal static string AccountAlreadyActivated {
            get {
                return ResourceManager.GetString("AccountAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đang tạm khoá vì lý do: {0}. Vui lòng lòng truy cập lại sau vài phút nữa hoặc liên hệ với quản trị nếu tiếp tục không truy cập được.
        /// </summary>
        internal static string AccountBlock {
            get {
                return ResourceManager.GetString("AccountBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã hết hạn.
        /// </summary>
        internal static string AccountExpired {
            get {
                return ResourceManager.GetString("AccountExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chưa được kích hoạt. Vui lòng kích hoạt tài khoản để có thể truy nhập hệ thống.
        /// </summary>
        internal static string AccountNotActivated {
            get {
                return ResourceManager.GetString("AccountNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công!.
        /// </summary>
        internal static string ChangePassSuccess {
            get {
                return ResourceManager.GetString("ChangePassSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&apos;validator_success_message&apos;&gt;Email có thể sử dụng được&lt;/span&gt;.
        /// </summary>
        internal static string EmailAvailable {
            get {
                return ResourceManager.GetString("EmailAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&apos;validator_error_message&apos;&gt;Email này đã được sử dụng, hãy chọn email khác&lt;/span&gt;.
        /// </summary>
        internal static string EmailUnAvailable {
            get {
                return ResourceManager.GetString("EmailUnAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kích hoạt không đúng, vui lòng kiểm tra lại.
        /// </summary>
        internal static string IncorrectActivationCode {
            get {
                return ResourceManager.GetString("IncorrectActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản không đúng, vui lòng kiểm tra lại.
        /// </summary>
        internal static string IncorrectUsername {
            get {
                return ResourceManager.GetString("IncorrectUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không hợp lệ! Tên đăng nhập dài ít nhất 3 ký tự bao gồm các ký tự, chữ số, dấu &quot;_&quot; và phải bắt đầu bằng một ký tự. Không chấp nhận tiếng Việt có dấu.
        /// </summary>
        internal static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại! Username hoặc mật khẩu không đúng.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng, xin vui lòng thử lại..
        /// </summary>
        internal static string OldPassInvalid {
            get {
                return ResourceManager.GetString("OldPassInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập không được chứa các từ khoà dành riêng như &apos;admin&apos;, &apos;root&apos;. Bạn vui lòng kiểm tra lại.
        /// </summary>
        internal static string ReservedUsername {
            get {
                return ResourceManager.GetString("ReservedUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản &lt;strong&gt;{0}&lt;/strong&gt; đã được reset mật khẩu. Một email có chứa mật khẩu mới đã được gửi đến địa chỉ &lt;strong&gt;{1} &lt;/strong&gt;. Vui lòng truy cập email để biết mật khẩu mới của bạn.
        /// </summary>
        internal static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&apos;validator_success_message&apos;&gt;Tên đăng nhập có thể sử dụng được&lt;/span&gt;.
        /// </summary>
        internal static string UsernameAvailable {
            get {
                return ResourceManager.GetString("UsernameAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&apos;validator_error_message&apos;&gt;Tên đăng nhập này đã được sử dụng, hãy chọn tên khác&lt;/span&gt;.
        /// </summary>
        internal static string UsernameUnAvailable {
            get {
                return ResourceManager.GetString("UsernameUnAvailable", resourceCulture);
            }
        }
    }
}
